---
- hosts: all  # Applique ce playbook à tous les hôtes définis dans l'inventaire
  gather_facts: true  # Récupère des informations système sur les hôtes avant d'exécuter les tâches
  become: true  # Exécute les commandes avec des privilèges administrateur

  roles:  # Liste des rôles Ansible à exécuter dans l'ordre
    - install_docker  # Installe Docker sur les hôtes
    - copy_env  # Copie les fichiers d'environnement nécessaires (ex: .env pour les variables d’application)
    - create_network  # Crée les networks Docker et le volume
    - launch_database  # Déploie et démarre la base de données
    - launch_app  # Déploie et démarre le backend
    - launch_proxy  # Déploie et configure le proxy
    - launch_front  # Déploie et démarre le front
