name: Ansible Deployment
on:
  workflow_run:
    workflows: ["CI devops 2025 - Main"]
    types:
      - completed

jobs:      
  deploy-ansible:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.head_branch == 'main'  # Exécuter seulement sur main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H theotim.colin-de-verdiere.takima.cloud >> ~/.ssh/known_hosts

      - name: Create application environment file on remote server
        run: echo "${{ secrets.POINT_ENV }}" | ssh -i ~/.ssh/id_rsa admin@theotim.colin-de-verdiere.takima.cloud "sudo tee /opt/app/application.env > /dev/null"


      - name: Run Ansible Playbook on remote server
        run: ansible-playbook -i inventories/setup.yml playbook.yml
        working-directory: ansible
