name: Ansible
on:
  workflow_run:
    workflows: ["CI devops 2025 - Main"]
    types:
      - completed

jobs:      
  push-ansible:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.head_branch == 'main'  # Filtre pour ne s'exécuter que sur main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create application environment file
        run: echo "${{ secrets.POINT_ENV }}" > /opt/app/application.env

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: sudo ansible-playbook -i inventories/setup.yml playbook.yml
