name: CI devops 2025 - Main
on:
  workflow_run:
    workflows: ["CI devops 2025 - Develop"]
    types:
      - completed
jobs:      
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    if: github.event.worflow_run.head_branch == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKER_HUB_NAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKER_HUB_NAME }}/tp-devops-database:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKER_HUB_NAME }}/tp-devops-httpd:latest
          push: true
